# Generated by Django 3.2.8 on 2021-10-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewbigrams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewbigrams',
            name='Distance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='reviewbigrams',
            name='Score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
