# Generated by Django 3.2.8 on 2021-11-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211019_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Topic',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='TopicScore',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
    ]
