# Generated by Django 3.2.8 on 2021-12-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20211114_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ReviewID',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
