# Generated by Django 3.2.8 on 2021-12-21 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_reviewid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicID', models.CharField(default='N/A', max_length=40)),
                ('TopicNum', models.IntegerField(default=0)),
                ('TopicName', models.CharField(default='N/A', max_length=200)),
                ('TopicExamples', models.CharField(default='N/A', max_length=2000)),
                ('TScore', models.DecimalField(decimal_places=4, default=0, max_digits=4)),
                ('ReviewKey', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='topic_encrypt', to='reviews.review')),
            ],
        ),
    ]
