# Generated by Django 3.2.8 on 2021-12-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
