# Generated by Django 3.2.8 on 2021-12-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.CharField(default='N/A', max_length=100)),
                ('WScore', models.DecimalField(decimal_places=4, default=0, max_digits=4)),
                ('POS_Tag', models.CharField(default='N/A', max_length=10)),
                ('WTopicNum', models.IntegerField(default=0)),
                ('ModelKey', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='word_encrypt', to='reviews.reviewmodel')),
            ],
        ),
    ]
