# Generated by Django 3.2.8 on 2021-12-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_wordscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordscores',
            name='WTopicScore',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
    ]
