# Generated by Django 3.2.8 on 2021-12-23 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_wordscores_wtopicscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_LearnedAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating_Estimate', models.DecimalField(decimal_places=4, default=0, max_digits=4)),
                ('SentimentTrend', models.CharField(default='N/A', max_length=500)),
                ('ReviewKey', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='revattrs_encrypt', to='reviews.review')),
            ],
        ),
    ]
