# Generated by Django 3.2.8 on 2021-12-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_review_learnedattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Rating_Estimate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='review',
            name='SentimentTrend',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.DeleteModel(
            name='Review_LearnedAttributes',
        ),
    ]
